feat: database update step

diff --git a/.github/workflows/compute.yml b/.github/workflows/compute.yml
--- a/.github/workflows/compute.yml
+++ b/.github/workflows/compute.yml
@@ -42,3 +42,17 @@ jobs:
       - name: Execute directive
         run: npx tsx ./src/main.ts
         id: automated-merging
+
+      - name: Commit and Push DB updates
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          git add database/sql.db
+          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
+            git commit -m "chore: [skip ci] updated database" || echo "Lint-staged check failed"
+            git push origin main
+          else
+            echo "No changes to commit"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
